name: Node.js CI with Mocha

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: install dependencies
        run: npm install
      - name: Run Eslint
        run: npm run lint

  codeql:
    runs-on: ubuntu-latest
    needs: [lint]
    permissions:
      security-events: write
      actions: read #ใช้เพื่อให้ job นี้มีสิทธิ์ดึงข้อมูลของ GitHub Actions (เช่น workflow runs, job details, logs)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Initialize codeql
        uses: github/codeql-action/init@v3
        with:
          languages: javascript-typescript
      - name: Perform codeql analysis
        uses: github/codeql-action/analyze@v3

  build:
    runs-on: ubuntu-latest
    needs: [lint,codeql]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name : Run a Hellow World action
        uses: actions/hello-world-docker-action@v1

      - name: Install dependencies
        run: npm install

      - name: Set executable permissions for Mocha
        run: chmod +x ./node_modules/.bin/mocha

      - name: Run tests
        run: npm test

